export const formFields=[
    {
     id:1,
     label:"Sample No.",
     type:"text",
     name:"sampleNo",
     placeholder:"CL23004336",
     value:"",    
    },
    {
    id:2,
    label:"Sample Date",
    type:"date",
    name:"sampleDate",
    placeholder:"20/11/2023",
    value:"",    
   },
   {
   id:3,
   label:"Rep. No.",
   type:"text",
   name:"repNo",
   placeholder:"B23007650",
   value:"",    
  },
  {
  id:4,
  label:"Rep. Time",
  type:"time",
  name:"repTime",
  placeholder:"02:28",
  value:"",    
 },
 {
    id:5,
    label:"Ward Name",
    type:"text",
    name:"wardName",
    placeholder:"",
    value:"",    
   },
   {
    id:6,
    label:"Pt. Name",
    type:"text",
    name:"ptName",
    placeholder:"RV. GIRIJAKUMARI",
    value:"",    
   },
   {
    id:7,
    label:"Gender",
    type:"radio",
    name:"gender",
    placeholder:"Female",
    value:"",    
   },
   {
    id:8,
    label:"Age",
    type:"Number",
    name:"age",
    placeholder:"63",
    value:"",    
   },
   {
    id:9,
    label:"Samp. Time",
    type:"time",
    name:"sampTime",
    placeholder:"02:24",
    value:"",    
   },
   {
    id:10,
    label:"Kit / Material",
    type:"Number",
    name:"repTime",
    placeholder:"02:28",
    value:"",    
   },
   {
    id:11,
    label:"Lab Doctor",
    type:"text",
    name:"labDoctor",
    placeholder:"DINESH.M",
    value:"",    
   },
   {
    id:12,
    label:"Lab.Tech.",
    type:"text",
    name:"labTech",
    placeholder:"Srikanth R",
    value:"",    
   },
   {
    id:13,
    label:"Pat.No.",
    type:"Number",
    name:"patNo.",
    placeholder:"231120002",
    value:"",    
   },
   {
    id:14,
    label:"Rep. TAT",
    type:"Number",
    name:"repTat",
    placeholder:"-65159848",
    value:"",    
   },
   {
    id:15,
    label:"Specimen",
    type:"text",
    name:"specimen",
    placeholder:"",
    value:"",    
   },
   {
    id:16,
    label:"Tests",
    type:"text",
    name:"tests",
    placeholder:"LIVER FUNCTION TEST - T0206",
    value:"",    
   },
   {
    id:17,
    label:"Remarks",
    type:"time",
    name:"repTime",
    placeholder:"02:28",
    value:"",    
   },
   // {
   //  id:18,
   //  label:"",
   //  type:"text",
   //  name:"",
   //  placeholder:"",
   //  value:"",    
   // },
   {
    id:19,
    label:"Std. TAT",
    type:"text",
    name:"stdTat",
    placeholder:"",
    value:"",    
   },
   {
    id:20,
    label:"UMR No.",
    type:"Number",
    name:"umrNo",
    placeholder:"2307960",
    value:"",    
   },

]